from paillier import generate_paillier_keypair, encrypt, encrypted_addition
import random
from typing import Tuple

def deterministic_encrypt(m: int, public_key: Tuple[int, int]) -> int:
    """
    Encryption function that is deterministic (using a fixed r = 1)
    for the purposes of the zero-knowledge proof.
    NOT SECURE for production use!
    """
    n, g = public_key
    return pow(g, m, n ** 2)

class ZeroKnowledgeProofQuadratic:
    def __init__(self, E_pubkey: Tuple[int, int], U_pubkey: Tuple[int, int]) -> None:
        self.E_pubkey: Tuple[int, int] = E_pubkey  # Public key for encrypting votes (E_key)
        self.U_pubkey: Tuple[int, int] = U_pubkey  # Public key for encrypting cost (U_key)

    def generate_proof(self, v: int) -> Tuple[Tuple[int, int], int]:
        """
        Generates a ZKP that shows that the cost c = v^2 without revealing v.
        
        :param v: The plain number of votes.
        :return: A tuple (proof_commitment, r) where proof_commitment is (E_r, U_r_squared)
                 and r is the random value used.
        """
        # Step 1: Generate a random value r.
        r: int = random.randint(1, 1000)
        
        # Step 2: Deterministically encrypt r and r^2.
        E_r: int = deterministic_encrypt(r, self.E_pubkey)
        U_r_squared: int = deterministic_encrypt(r ** 2, self.U_pubkey)
        
        proof_commitment: Tuple[int, int] = (E_r, U_r_squared)
        return proof_commitment, r

    def respond_to_challenge(self, r: int, v: int, challenge: int) -> int:
        """
        Responds to the server's challenge.
        
        :param r: The random value generated by the client.
        :param v: The plain number of votes.
        :param challenge: The challenge sent by the server.
        :return: The response z = r + challenge * v.
        """
        z: int = r + challenge * v
        return z

    def verify_proof(
        self,
        v: int,
        proof_commitment: Tuple[int, int],
        z: int,
        challenge: int,
        cost: int = None
    ) -> bool:
        """
        The server verifies that the cost is the square of the votes.
        
        :param v: The plain number of votes.
        :param proof_commitment: A tuple (E_r, U_r_squared) from the client.
        :param z: The client's response to the challenge.
        :param challenge: The challenge sent by the server.
        :param cost: Optionally, the cost to verify. If None, cost is assumed to be v^2.
        :return: True if the proof is valid, False otherwise.
        """
        if cost is None:
            cost = v ** 2

        E_r, U_r_squared = proof_commitment

        # For E_key:
        n_E: int = self.E_pubkey[0]
        left_E: int = deterministic_encrypt(z, self.E_pubkey)
        # right_E = E(r) * (deterministic_encrypt(v))^challenge, using the multiplicative property
        right_E: int = (E_r * pow(deterministic_encrypt(v, self.E_pubkey), challenge, n_E ** 2)) % (n_E ** 2)

        # For U_key:
        n_U: int = self.U_pubkey[0]
        left_U: int = deterministic_encrypt(z ** 2, self.U_pubkey)
        right_U: int = (U_r_squared * pow(deterministic_encrypt(cost, self.U_pubkey), challenge, n_U ** 2)) % (n_U ** 2)

        return left_E == right_E and left_U == right_U

def main() -> None:
    # Setup Paillier keypairs for votes (E_key) and cost (U_key)
    E_pubkey, E_privkey = generate_paillier_keypair()
    U_pubkey, U_privkey = generate_paillier_keypair()

    # The client votes with 3 votes.
    v: int = 3
    cost: int = v ** 2  # The correct cost should be v^2.

    # Encrypt the number of votes and the cost using the (randomized) encrypt function.
    E_v: int = encrypt(v, E_pubkey)
    U_c: int = encrypt(cost, U_pubkey)

    # Start the ZKP protocol using deterministic encryption for proof purposes.
    zkp = ZeroKnowledgeProofQuadratic(E_pubkey, U_pubkey)
    proof_commitment, r = zkp.generate_proof(v)

    # The server sends a random challenge.
    challenge: int = random.randint(1, 100)

    # The client responds to the challenge.
    z: int = zkp.respond_to_challenge(r, v, challenge)

    # The server verifies the proof with the correct cost.
    is_valid: bool = zkp.verify_proof(v, proof_commitment, z, challenge)
    print(f"La prova ZKP è valida? {'Sì' if is_valid else 'No'}")

    # Fraud attempt: the client tries to cheat by using a false cost.
    fake_cost: int = 1  # False cost
    is_valid_fake: bool = zkp.verify_proof(v, proof_commitment, z, challenge, cost=fake_cost)
    print(f"Tentativo di frode: la prova falsa è valida? {'Sì' if is_valid_fake else 'No'}")

if __name__ == "__main__":
    main()
